# Generated by Django 5.1.13 on 2025-11-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabricante', models.CharField(choices=[('S', 'Sony'), ('N', 'Nintendo'), ('F', 'Fabricante3')], max_length=1)),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(max_length=30)),
                ('sede', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudioSede', to='examen.sede')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('ventas_estimadas', models.PositiveIntegerField()),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegoEstudio', to='examen.estudio')),
                ('plataforma', models.ManyToManyField(related_name='videojuegoPlataformas', to='examen.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveIntegerField()),
                ('anyo_analisis', models.PositiveIntegerField()),
                ('nombre_critico', models.CharField(max_length=30)),
                ('videojuego', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisisVideojuego', to='examen.videojuego')),
            ],
        ),
    ]
