# Generated by Django 5.1.13 on 2025-11-04 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisis',
            name='videojuego',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisisVideojuego', to='examen.videojuego'),
        ),
        migrations.AlterField(
            model_name='estudio',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudioSede', to='examen.sede'),
        ),
        migrations.AlterField(
            model_name='videojuego',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegoEstudio', to='examen.estudio'),
        ),
    ]
